export const LOGIN_REQUEST_STARTS = "LOGIN_REQUEST_STARTS";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED";
export const LOGIN_REQUEST_ENDS = "LOGIN_REQUEST_ENDS";

export const LOGIN_PERFORM_LOGIN = "LOGIN_PERFORM_LOGIN";
export const LOGIN_RESET_STATE = "LOGIN_RESET_STATE";
export const LOGIN_LOGOUT = "LOGIN_LOGOUT";
export const LOGIN_PERFORM_REGISTER = "LOGIN_PERFORM_REGISTER";
export const LOGIN_PERFORM_UPDATE = "LOGIN_PERFORM_UPDATE";
export const LOGIN_PERFORM_UPDATE_WITH_IMAGE =
  "LOGIN_PERFORM_UPDATE_WITH_IMAGE";
export const LOGIN_RESET_ERROR = "LOGIN_RESET_ERROR";

//GET AVATAR

export const AVATAR_REQUEST_STARTS = "AVATAR_REQUEST_STARTS";
export const AVATAR_REQUEST_ENDS = "AVATAR_REQUEST_ENDS";
export const AVATAR_REQUEST_FAILED = "AVATAR_REQUEST_FAILED";
export const AVATAR_REQUEST_SUCCESS = "AVATAR_REQUEST_SUCCESS";
export const AVATAR_RESET_STATE = "AVATAR_RESET_STATE";
export const AVATAR_PERFORM_PROFILE = "AVATAR_PERFORM_PROFILE";

//VEHICLES
export const VEHICLE_PERFORM_FETCH = "VEHICLE_PERFORM_FETCH";
export const VEHICLE_REQUEST_STARTS = "VEHICLE_REQUEST_STARTS";
export const VEHICLE_REQUEST_ENDS = "VEHICLE_REQUEST_ENDS";
export const VEHICLE_REQUEST_FAILED = "VEHICLE_REQUEST_FAILED";
export const VEHICLE_REQUEST_SUCCESS = "VEHICLE_REQUEST_SUCCESS";
export const VEHICLE_RESET_STAT = "VEHICLE_RESET_STAT";
export const VEHICLE_RESET_ERRO = "VEHICLE_RESET_ERRO";
export const VEHICLE_RESET_STATE = "VEHICLE_RESET_STATE";
export const VEHICLE_RESET_ERROR = "VEHICLE_RESET_ERROR";

//CREATE AND UPDATE VEHICLE

export const VEHICLE_CREATE_REQUEST_STARTS = "VEHICLE_CREATE_REQUEST_STARTS";
export const VEHICLE_CREATE_REQUEST_ENDS = "VEHICLE_CREATE_REQUEST_ENDS";
export const VEHICLE_CREATE_REQUEST_FAILED = "VEHICLE_CREATE_REQUEST_FAILED";
export const VEHICLE_CREATE_REQUEST_SUCCESS = "VEHICLE_CREATE_REQUEST_SUCCESS";
export const VEHICLE_CREATE_RESET_STATE = "VEHICLE_CREATE_RESET_STATE";
export const VEHICLE_CREATE_RESET_ERROR = "VEHICLE_CREATE_RESET_ERROR";
export const VEHICLE_CREATE_PERFORM_FETCH = "VEHICLE_CREATE_PERFORM_FETCH";
export const VEHICLE_UPDATE_PERFORM_FETCH = "VEHICLE_UPDATE_PERFORM_FETCH";
export const VEHICLE_DELETE_PERFORM_FETCH = "VEHICLE_DELETE_PERFORM_FETCH";


//TRAVELS

export const TRAVELS_REQUEST_STARTS='TRAVELS_REQUEST_STARTS';
export const TRAVELS_REQUEST_ENDS='TRAVELS_REQUEST_ENDS';
export const TRAVELS_REQUEST_FAILED='TRAVELS_REQUEST_FAILED';
export const TRAVELS_REQUEST_SUCCESS='TRAVELS_REQUEST_SUCCESS';
export const TRAVELS_PERFORM_FETCH='TRAVELS_PERFORM_FETCH';
export const TRAVELS_RESET_STATE='TRAVELS_RESET_STATE';
export const TRAVELS_RESET_ERROR='TRAVELS_RESET_ERROR';

//CREATE AND UPDATE TRAVELS

export const TRAVELS_CREATE_REQUEST_STARTS='TRAVELS_CREATE_REQUEST_STARTS';
export const TRAVELS_CREATE_REQUEST_ENDS='TRAVELS_CREATE_REQUEST_ENDS';
export const TRAVELS_CREATE_REQUEST_FAILED='TRAVELS_CREATE_REQUEST_FAILED';
export const TRAVELS_CREATE_REQUEST_SUCCESS='TRAVELS_CREATE_REQUEST_SUCCESS';
export const TRAVELS_CREATE_PERFORM_FETCH='TRAVELS_CREATE_PERFORM_FETCH';
export const TRAVELS_UPDATE_PERFORM_FETCH='TRAVELS_UPDATE_PERFORM_FETCH';
export const TRAVELS_DELETE_PERFORM_FETCH='TRAVELS_DELETE_PERFORM_FETCH';
export const TRAVELS_CREATE_RESET_STATE='TRAVELS_CREATE_RESET_STATE';
export const TRAVELS_CREATE_RESET_ERROR='TRAVELS_CREATE_RESET_ERROR';
 
//DRIVERS

export const DRIVERS_REQUEST_STARTS='DRIVERS_REQUEST_STARTS';
export const DRIVERS_REQUEST_ENDS='DRIVERS_REQUEST_ENDS';
export const DRIVERS_REQUEST_FAILED='DRIVERS_REQUEST_FAILED';
export const DRIVERS_REQUEST_SUCCESS='DRIVERS_REQUEST_SUCCESS';
export const DRIVERS_PERFORM_FETCH='DRIVERS_PERFORM_FETCH';
export const DRIVERS_RESET_STATE='DRIVERS_RESET_STATE';
export const DRIVERS_RESET_ERROR='DRIVERS_RESET_ERROR';

// CREATE AND UPDATE DRIVERS

export const DRIVER_CREATE_REQUEST_FAILED='DRIVER_CREATE_REQUEST_FAILED';
export const DRIVER_CREATE_REQUEST_SUCCESS='DRIVER_CREATE_REQUEST_SUCCESS';
export const DRIVER_CREATE_REQUEST_ENDS='DRIVER_CREATE_REQUEST_ENDS';
export const DRIVER_CREATE_REQUEST_STARTS='DRIVER_CREATE_REQUEST_STARTS';
export const DRIVER_CREATE_PERFORM_FETCH='DRIVER_CREATE_PERFORM_FETCH';
export const DRIVER_UPDATE_PERFORM_FETCH='DRIVER_UPDATE_PERFORM_FETCH';
export const DRIVER_DELETE_PERFORM_FETCH='DRIVER_DELETE_PERFORM_FETCH';
export const DRIVER_CREATE_RESET_STATE='DRIVER_CREATE_RESET_STATE';
export const DRIVER_CREATE_RESET_ERROR='DRIVER_CREATE_RESET_ERROR';


//STATS

export const STATS_REQUEST_STARTS='STATS_REQUEST_STARTS,';
export const STATS_REQUEST_ENDS='STATS_REQUEST_ENDS,';
export const STATS_REQUEST_FAILED='STATS_REQUEST_FAILED,';
export const STATS_REQUEST_SUCCESS='STATS_REQUEST_SUCCESS,';
export const STATS_PERFORM_FETCH='STATS_PERFORM_FETCH,';
export const STATS_RESET_STATE='STATS_RESET_STATE';
export const STATS_RESET_ERROR='STATS_RESET_ERROR';