export const LOGIN_REQUEST_STARTS = "LOGIN_REQUEST_STARTS";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED";
export const LOGIN_REQUEST_ENDS = "LOGIN_REQUEST_ENDS";

export const LOGIN_PERFORM_LOGIN = "LOGIN_PERFORM_LOGIN";
export const LOGIN_RESET_STATE = "LOGIN_RESET_STATE";
export const LOGIN_LOGOUT = "LOGIN_LOGOUT";
export const LOGIN_PERFORM_REGISTER = "LOGIN_PERFORM_REGISTER";
export const LOGIN_PERFORM_UPDATE = "LOGIN_PERFORM_UPDATE";
export const LOGIN_PERFORM_UPDATE_WITH_IMAGE =
  "LOGIN_PERFORM_UPDATE_WITH_IMAGE";
export const LOGIN_RESET_ERROR = "LOGIN_RESET_ERROR";

//GET AVATAR

export const AVATAR_REQUEST_STARTS = "AVATAR_REQUEST_STARTS";
export const AVATAR_REQUEST_ENDS = "AVATAR_REQUEST_ENDS";
export const AVATAR_REQUEST_FAILED = "AVATAR_REQUEST_FAILED";
export const AVATAR_REQUEST_SUCCESS = "AVATAR_REQUEST_SUCCESS";
export const AVATAR_RESET_STATE = "AVATAR_RESET_STATE";
export const AVATAR_PERFORM_PROFILE = "AVATAR_PERFORM_PROFILE";

//VEHICLES
export const VEHICLE_PERFORM_FETCH = "VEHICLE_PERFORM_FETCH";
export const VEHICLE_REQUEST_STARTS = "VEHICLE_REQUEST_STARTS";
export const VEHICLE_REQUEST_ENDS = "VEHICLE_REQUEST_ENDS";
export const VEHICLE_REQUEST_FAILED = "VEHICLE_REQUEST_FAILED";
export const VEHICLE_REQUEST_SUCCESS = "VEHICLE_REQUEST_SUCCESS";
export const VEHICLE_RESET_STAT = "VEHICLE_RESET_STAT";
export const VEHICLE_RESET_ERRO = "VEHICLE_RESET_ERRO";
export const VEHICLE_RESET_STATE = "VEHICLE_RESET_STATE";
export const VEHICLE_RESET_ERROR="VEHICLE_RESET_ERROR";
